name: GH200 Demo
on: push
jobs:
  first-job:
    runs-on: windows-2022
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
  second-job:
    needs: first-job
    runs-on: ubuntu-22.04
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"       
